"""add_diagnosis_tables

Revision ID: 1c90b2c5ff87
Revises: e54a8a4d88c9
Create Date: 2026-02-02 22:56:11.875742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '1c90b2c5ff87'
down_revision = 'e54a8a4d88c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(), nullable=False),
    sa.Column('meals_analyzed', sa.Integer(), nullable=False),
    sa.Column('symptoms_analyzed', sa.Integer(), nullable=False),
    sa.Column('date_range_start', sa.DateTime(), nullable=False),
    sa.Column('date_range_end', sa.DateTime(), nullable=False),
    sa.Column('sufficient_data', sa.Boolean(), nullable=False),
    sa.Column('claude_model', sa.String(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_tokens', sa.Integer(), nullable=True),
    sa.Column('web_search_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_runs_id'), 'diagnosis_runs', ['id'], unique=False)
    op.create_index(op.f('ix_diagnosis_runs_run_timestamp'), 'diagnosis_runs', ['run_timestamp'], unique=False)
    op.create_index(op.f('ix_diagnosis_runs_user_id'), 'diagnosis_runs', ['user_id'], unique=False)
    op.create_table('diagnosis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('confidence_level', sa.String(), nullable=False),
    sa.Column('immediate_correlation', sa.Integer(), nullable=False),
    sa.Column('delayed_correlation', sa.Integer(), nullable=False),
    sa.Column('cumulative_correlation', sa.Integer(), nullable=False),
    sa.Column('times_eaten', sa.Integer(), nullable=False),
    sa.Column('times_followed_by_symptoms', sa.Integer(), nullable=False),
    sa.Column('state_matters', sa.Boolean(), nullable=False),
    sa.Column('problematic_states', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('associated_symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['diagnosis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_results_id'), 'diagnosis_results', ['id'], unique=False)
    op.create_index(op.f('ix_diagnosis_results_ingredient_id'), 'diagnosis_results', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_results_run_id'), 'diagnosis_results', ['run_id'], unique=False)
    op.create_table('diagnosis_citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_title', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['diagnosis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_citations_id'), 'diagnosis_citations', ['id'], unique=False)
    op.create_index(op.f('ix_diagnosis_citations_result_id'), 'diagnosis_citations', ['result_id'], unique=False)
    op.create_table('diagnosis_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('eliminated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['diagnosis_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_feedback_id'), 'diagnosis_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_diagnosis_feedback_result_id'), 'diagnosis_feedback', ['result_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_feedback_user_id'), 'diagnosis_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnosis_feedback_user_id'), table_name='diagnosis_feedback')
    op.drop_index(op.f('ix_diagnosis_feedback_result_id'), table_name='diagnosis_feedback')
    op.drop_index(op.f('ix_diagnosis_feedback_id'), table_name='diagnosis_feedback')
    op.drop_table('diagnosis_feedback')
    op.drop_index(op.f('ix_diagnosis_citations_result_id'), table_name='diagnosis_citations')
    op.drop_index(op.f('ix_diagnosis_citations_id'), table_name='diagnosis_citations')
    op.drop_table('diagnosis_citations')
    op.drop_index(op.f('ix_diagnosis_results_run_id'), table_name='diagnosis_results')
    op.drop_index(op.f('ix_diagnosis_results_ingredient_id'), table_name='diagnosis_results')
    op.drop_index(op.f('ix_diagnosis_results_id'), table_name='diagnosis_results')
    op.drop_table('diagnosis_results')
    op.drop_index(op.f('ix_diagnosis_runs_user_id'), table_name='diagnosis_runs')
    op.drop_index(op.f('ix_diagnosis_runs_run_timestamp'), table_name='diagnosis_runs')
    op.drop_index(op.f('ix_diagnosis_runs_id'), table_name='diagnosis_runs')
    op.drop_table('diagnosis_runs')
    # ### end Alembic commands ###
