"""Initial schema with all models

Revision ID: 431a799ebeb8
Revises: a02d9fd847b2
Create Date: 2026-01-27 22:28:10.486293

"""

revision = "431a799ebeb8"
down_revision = "a02d9fd847b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
