"""Initial schema with all models and country field

Revision ID: a02d9fd847b2
Revises:
Create Date: 2026-01-27 21:57:28.894445

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "a02d9fd847b2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eval_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("eval_type", sa.String(length=50), nullable=False),
        sa.Column("precision", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("recall", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("f1_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("accuracy", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("num_test_cases", sa.Integer(), nullable=True),
        sa.Column("test_data_source", sa.String(length=255), nullable=True),
        sa.Column(
            "detailed_results", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "execution_time_seconds", sa.Numeric(precision=8, scale=2), nullable=True
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_eval_runs_created_at", "eval_runs", ["created_at"], unique=False
    )
    op.create_index("idx_eval_runs_eval_type", "eval_runs", ["eval_type"], unique=False)
    op.create_index(
        "idx_eval_runs_model_name", "eval_runs", ["model_name"], unique=False
    )
    op.create_table(
        "ingredient_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["ingredient_categories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("normalized_name"),
    )
    op.create_index(
        "idx_ingredient_categories_level",
        "ingredient_categories",
        ["level"],
        unique=False,
    )
    op.create_index(
        "idx_ingredient_categories_parent_id",
        "ingredient_categories",
        ["parent_id"],
        unique=False,
    )
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ingredients_normalized_name",
        "ingredients",
        ["normalized_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingredients_normalized_name"),
        "ingredients",
        ["normalized_name"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "data_exports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_path", sa.String(length=512), nullable=True),
        sa.Column("format", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_data_exports_status", "data_exports", ["status"], unique=False)
    op.create_index(
        "idx_data_exports_user_id", "data_exports", ["user_id"], unique=False
    )
    op.create_table(
        "ingredient_category_relations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["ingredient_categories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"], ["ingredients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ingredient_id", "category_id", name="uq_ingredient_category"
        ),
    )
    op.create_index(
        "idx_ingr_cat_rel_category_id",
        "ingredient_category_relations",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        "idx_ingr_cat_rel_ingredient_id",
        "ingredient_category_relations",
        ["ingredient_id"],
        unique=False,
    )
    op.create_table(
        "meals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("image_path", sa.String(length=512), nullable=True),
        sa.Column("user_notes", sa.Text(), nullable=True),
        sa.Column("ai_raw_response", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_meals_country", "meals", ["country"], unique=False)
    op.create_index("idx_meals_timestamp", "meals", ["timestamp"], unique=False)
    op.create_index("idx_meals_user_id", "meals", ["user_id"], unique=False)
    op.create_table(
        "symptoms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("raw_description", sa.Text(), nullable=False),
        sa.Column(
            "clarification_history",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("structured_type", sa.String(length=255), nullable=True),
        sa.Column("severity", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_symptoms_structured_type", "symptoms", ["structured_type"], unique=False
    )
    op.create_index("idx_symptoms_timestamp", "symptoms", ["timestamp"], unique=False)
    op.create_index("idx_symptoms_user_id", "symptoms", ["user_id"], unique=False)
    op.create_table(
        "user_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("disclaimer_acknowledged", sa.Boolean(), nullable=True),
        sa.Column(
            "disclaimer_acknowledged_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("data_processing_consent", sa.Boolean(), nullable=True),
        sa.Column(
            "data_processing_consent_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("privacy_policy_version", sa.String(length=20), nullable=True),
        sa.Column("demographics_consent", sa.Boolean(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("height_cm", sa.Integer(), nullable=True),
        sa.Column("gender", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_user_settings_user_id"),
    )
    op.create_table(
        "meal_ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meal_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("RAW", "COOKED", "PROCESSED", name="ingredientstate"),
            nullable=False,
        ),
        sa.Column("quantity_description", sa.String(length=255), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"], ["ingredients.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["meal_id"], ["meals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_meal_ingredients_ingredient_id",
        "meal_ingredients",
        ["ingredient_id"],
        unique=False,
    )
    op.create_index(
        "idx_meal_ingredients_meal_id", "meal_ingredients", ["meal_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_meal_ingredients_meal_id", table_name="meal_ingredients")
    op.drop_index("idx_meal_ingredients_ingredient_id", table_name="meal_ingredients")
    op.drop_table("meal_ingredients")
    op.drop_table("user_settings")
    op.drop_index("idx_symptoms_user_id", table_name="symptoms")
    op.drop_index("idx_symptoms_timestamp", table_name="symptoms")
    op.drop_index("idx_symptoms_structured_type", table_name="symptoms")
    op.drop_table("symptoms")
    op.drop_index("idx_meals_user_id", table_name="meals")
    op.drop_index("idx_meals_timestamp", table_name="meals")
    op.drop_index("idx_meals_country", table_name="meals")
    op.drop_table("meals")
    op.drop_index(
        "idx_ingr_cat_rel_ingredient_id", table_name="ingredient_category_relations"
    )
    op.drop_index(
        "idx_ingr_cat_rel_category_id", table_name="ingredient_category_relations"
    )
    op.drop_table("ingredient_category_relations")
    op.drop_index("idx_data_exports_user_id", table_name="data_exports")
    op.drop_index("idx_data_exports_status", table_name="data_exports")
    op.drop_table("data_exports")
    op.drop_table("users")
    op.drop_index(op.f("ix_ingredients_normalized_name"), table_name="ingredients")
    op.drop_index("idx_ingredients_normalized_name", table_name="ingredients")
    op.drop_table("ingredients")
    op.drop_index(
        "idx_ingredient_categories_parent_id", table_name="ingredient_categories"
    )
    op.drop_index("idx_ingredient_categories_level", table_name="ingredient_categories")
    op.drop_table("ingredient_categories")
    op.drop_index("idx_eval_runs_model_name", table_name="eval_runs")
    op.drop_index("idx_eval_runs_eval_type", table_name="eval_runs")
    op.drop_index("idx_eval_runs_created_at", table_name="eval_runs")
    op.drop_table("eval_runs")
    # ### end Alembic commands ###
