"""add_symptom_tags_and_episodes

Revision ID: c362f51a0834
Revises: 5acf901daa38
Create Date: 2026-01-30 21:53:42.009554

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "c362f51a0834"
down_revision = "5acf901daa38"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "meal_ingredients",
        "source",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'manual'::character varying"),
    )
    op.add_column(
        "symptoms",
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "symptoms", sa.Column("start_time", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "symptoms", sa.Column("end_time", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("symptoms", sa.Column("episode_id", sa.Integer(), nullable=True))
    op.add_column("symptoms", sa.Column("ai_elaborated", sa.Boolean(), nullable=True))
    op.add_column(
        "symptoms", sa.Column("ai_elaboration_response", sa.Text(), nullable=True)
    )
    op.add_column(
        "symptoms", sa.Column("user_edited_elaboration", sa.Boolean(), nullable=True)
    )
    op.create_index("idx_symptoms_episode_id", "symptoms", ["episode_id"], unique=False)
    op.create_index(
        "idx_symptoms_user_start_time",
        "symptoms",
        ["user_id", "start_time"],
        unique=False,
    )
    op.create_foreign_key(None, "symptoms", "symptoms", ["episode_id"], ["id"])
    op.add_column(
        "user_settings", sa.Column("ai_elaborate_symptoms", sa.Boolean(), nullable=True)
    )

    # Data migration: Convert existing symptoms to tag format
    op.execute("""
        UPDATE symptoms
        SET tags = jsonb_build_array(jsonb_build_object('name', LOWER(structured_type), 'severity', severity)),
            start_time = timestamp,
            ai_elaborated = FALSE
        WHERE tags IS NULL AND structured_type IS NOT NULL AND severity IS NOT NULL
    """)

    # Set default for ai_elaborate_symptoms in user_settings
    op.execute("""
        UPDATE user_settings
        SET ai_elaborate_symptoms = TRUE
        WHERE ai_elaborate_symptoms IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "ai_elaborate_symptoms")
    op.drop_constraint(None, "symptoms", type_="foreignkey")
    op.drop_index("idx_symptoms_user_start_time", table_name="symptoms")
    op.drop_index("idx_symptoms_episode_id", table_name="symptoms")
    op.drop_column("symptoms", "user_edited_elaboration")
    op.drop_column("symptoms", "ai_elaboration_response")
    op.drop_column("symptoms", "ai_elaborated")
    op.drop_column("symptoms", "episode_id")
    op.drop_column("symptoms", "end_time")
    op.drop_column("symptoms", "start_time")
    op.drop_column("symptoms", "tags")
    op.alter_column(
        "meal_ingredients",
        "source",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'manual'::character varying"),
    )
    # ### end Alembic commands ###
