#!/bin/bash
# Fetch secrets from AWS Secrets Manager and create .env file
# Run from /opt/bloaty directory

set -e

SECRET_NAME="bloaty/production"
REGION="${AWS_REGION:-eu-north-1}"
ENV_FILE=".env"

echo "Fetching secrets from AWS Secrets Manager..."

# Fetch secret JSON
SECRET_JSON=$(aws secretsmanager get-secret-value \
    --secret-id "$SECRET_NAME" \
    --region "$REGION" \
    --query SecretString \
    --output text)

if [ -z "$SECRET_JSON" ]; then
    echo "Error: Could not fetch secret $SECRET_NAME"
    exit 1
fi

# Parse and write to .env
echo "Writing $ENV_FILE..."

# Extract values using jq
ANTHROPIC_API_KEY=$(echo "$SECRET_JSON" | jq -r '.ANTHROPIC_API_KEY')
SESSION_SECRET_KEY=$(echo "$SECRET_JSON" | jq -r '.SESSION_SECRET_KEY')
POSTGRES_PASSWORD=$(echo "$SECRET_JSON" | jq -r '.POSTGRES_PASSWORD')
BACKUP_S3_BUCKET=$(echo "$SECRET_JSON" | jq -r '.BACKUP_S3_BUCKET // empty')

cat > "$ENV_FILE" << EOF
# Production environment - generated by fetch-secrets.sh
# DO NOT COMMIT THIS FILE

# Database
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/bloaty
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Redis
REDIS_URL=redis://redis:6379/0

# Anthropic API
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# Session security
SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
SESSION_COOKIE_SECURE=true

# Backup configuration
BACKUP_S3_BUCKET=${BACKUP_S3_BUCKET}
EOF

chmod 600 "$ENV_FILE"

echo "Done! Secrets written to $ENV_FILE"
echo "You can now start the application with:"
echo "  docker compose -f docker-compose.yml -f deploy/docker-compose.prod.yml up -d"
